config/routes.rb
Thesis::Application.routes.draw do

  get '/home' => 'pages#home'

  resources :parents

  resources :doctors
  

  root :to => 'pages#home'

end

app/models/doctor.rb
class Doctor < User

end

app/models/parent.rb
class Parent < User

end

app/models/user.rb
class User < ActiveRecord::Base

# ---------------------------- Mass assignment --------------------------
  attr_accessible :address, :email, :fullname, :phone, :specialty,
  								:password, :password_confirmation

  has_secure_password


# ---------------------------- Validations -----------------------------
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
  validates :fullname, presence: true, length: { within: 5..50 }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :address, presence: true
  validates :phone, presence: true

# ---------------------------- Callbacks -------------------------------
	before_save { |user| user.email = email.downcase }

# ------------------------- Instance Methods ---------------------------
  def is_parent?
    self.type == "Parent"
  end

  def is_doctor?
    self.type == "Doctor"
  end

end

# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  fullname        :string(255)
#  type            :string(255)
#  phone           :string(255)
#  address         :string(255)
#  specialty       :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/doctors_controller.rb
# encoding: utf-8

class DoctorsController < ApplicationController
  def new
    @user = Doctor.new
  end

  def create
    @user = Doctor.new(params[:doctor])
    @user.email = params[:doctor][:email].strip
    @user.password = params[:doctor][:password].strip
    @user.password_confirmation = params[:doctor][:password_confirmation].strip
    @user.fullname = params[:doctor][:fullname].strip
    @user.address = params[:doctor][:address].strip
    @user.phone = params[:doctor][:phone].strip
    @user.specialty = params[:doctor][:specialty].strip

    @user.valid?

    if @user.errors.empty?
      
      # @user.save

      flash[:success] = 'Ο λογαριασμός σας δημιουργήθηκε!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/parents_controller.rb
# encoding: utf-8

class ParentsController < ApplicationController
  def new
    @user = Parent.new
  end

  def create
    @user = Parent.new(params[:parent])
    @user.email = params[:parent][:email].strip
    @user.password = params[:parent][:password].strip
    @user.password_confirmation = params[:parent][:password_confirmation].strip
    @user.fullname = params[:parent][:fullname].strip
    @user.address = params[:parent][:address].strip
    @user.phone = params[:parent][:phone].strip

    @user.valid?

    if @user.errors.empty?
      
      @user.save

      flash[:success] = 'Ο λογαριασμός σας δημιουργήθηκε!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def render_sidebar?
		satisfy_controller_action_conditions?(
			'pages' => [:home])
	end

	def satisfy_controller_action_conditions?(conditions)
	    conditions.any? do |controller, actions|
	      (controller == params[:controller]) && 
	        (actions == :all || actions.include?(params[:action]))
	    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/doctors/edit.html.erb
<h1>Doctors#edit</h1>
<p>Find me in app/views/doctors/edit.html.erb</p>

app/views/doctors/index.html.erb
<h1>Doctors#index</h1>
<p>Find me in app/views/doctors/index.html.erb</p>

app/views/doctors/new.html.erb
<h1>Εγγραφή νέου Ειδικού Υγείας:</h1>

<%= form_for @user, html: {class: 'form-vertical'}  do |f| %>
	<fieldset>
		<legend>
			Παρακαλούμε εισάγετε τα στοιχεία σας προκειμένου να χρησιμοποιήσετε την εφαρμογή.
		</legend>
		
		<%= render 'shared/error_messages', obj: f.object %>	

		<div class="controls">
			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password, 'Κωδικός πρόσβασης' %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, 'Επιβεβαίωση κωδικού πρόσβασης' %>
			<%= f.password_field :password_confirmation %>

			<%= f.label :fullname, 'Ονοματεπώνυμο' %>
			<%= f.text_field :fullname %>

			<%= f.label :address, 'Διεύθυνση' %>
			<%= f.text_field :address %>

			<%= f.label :phone, 'Τηλέφωνο' %>
			<%= f.text_field :phone %>

			<%= f.label :specialty, 'Ειδικότητα' %>
			<%= f.text_field :specialty %>
		</div>
		<div class="form-actions">
			<%= f.submit 'Εγγραφή', class: 'btn btn-primary' %>
		</div>
	</fieldset>
<% end %>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/doctors/update.html.erb
<h1>Doctors#update</h1>
<p>Find me in app/views/doctors/update.html.erb</p>

app/views/layouts/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Sidebar</li>
      <li><%= link_to "Link1", "/path1"  %></li>
      <li><%= link_to "Link2", "/path2"  %></li>
      <li><%= link_to "Link3", "/path3"  %></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Thesis" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Thesis</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        
        <% if render_sidebar? %>
          <%= render partial: 'layouts/sidebar' %>
        <% end %>

        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; George Georgopoulos 2014</p>
      </footer>
      
      <!-- Debugging Info -->
      <%= debug(params) if Rails.env.development? %>
    </div> <!-- /container -->

  </body>
</html>

app/views/pages/home.html.erb
<h1 class="tac">Ατομικός Παιδιατρικός Φάκελος</h1>
<p class="tac">Καλώς ορίσατε στην εφαρμογή Ατομικού Παιδιατρικού Φακέλου για παιδιά!</p>

<hr>

<div class="offset2">
	<div class="tac span4">
		<h3><i>Είστε γονέας;</i></h3>
		<%= link_to 'Είσοδος γονέα', '', class: 'btn btn-primary' %> <i>ή</i> <br>
		<%= link_to 'Εγγραφή', new_parent_path %>

	</div>

	<div class="tac span4">
		<h3><i>Είστε ειδικός υγείας;</i></h3>
		<%= link_to 'Είσοδος Ειδικού Υγείας', '', class: 'btn btn-primary' %> <i>ή</i> <br>
		<%= link_to 'Εγγραφή', new_doctor_path %>
	</div>
</div>

app/views/parents/edit.html.erb
<h1>Parents#edit</h1>
<p>Find me in app/views/parents/edit.html.erb</p>

app/views/parents/index.html.erb
<h1>Parents#index</h1>
<p>Find me in app/views/parents/index.html.erb</p>

app/views/parents/new.html.erb
<h1>Εγγραφή νέου χρήστη</h1>

<%= form_for @user, html: {class: 'form-vertical'}  do |f| %>
	<fieldset>
		<legend>
			Παρακαλούμε εισάγετε τα στοιχεία σας προκειμένου να χρησιμοποιήσετε την εφαρμογή.
		</legend>
		
		<%= render 'shared/error_messages', obj: f.object %>	

		<div class="controls">
			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password, 'Κωδικός πρόσβασης' %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, 'Επιβεβαίωση κωδικού πρόσβασης' %>
			<%= f.password_field :password_confirmation %>

			<%= f.label :fullname, 'Ονοματεπώνυμο' %>
			<%= f.text_field :fullname %>

			<%= f.label :address, 'Διεύθυνση' %>
			<%= f.text_field :address %>

			<%= f.label :phone, 'Τηλέφωνο' %>
			<%= f.text_field :phone %>
		</div>
		<div class="form-actions">
			<%= f.submit 'Εγγραφή', class: 'btn btn-primary' %>
		</div>
	</fieldset>
<% end %>

app/views/parents/show.html.erb
<h1>Parents#show</h1>
<p>Find me in app/views/parents/show.html.erb</p>

app/views/parents/update.html.erb
<h1>Parents#update</h1>
<p>Find me in app/views/parents/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			<%= "#{obj.errors.count} λάθη εμπόδισαν την υποβολη αυτής της φόρμας." %>
		</div>
		<ul>
			<% obj.errors.messages.each do |attribute, msg| %>
				<% msg.each do |m| %>		
					<li>
						* <%= t attribute, scope: "activerecord.attributes.#{obj.class.name.downcase}" %>:
						 	 <%=  m %>
					</li>
				<% end %>
			<% end %>
		</ul>
	</div>
<% end%>